# Distance Measures

Suppose we have a set of points, called a $\textit{space}$. A $\textit{distance measure}$ on this space is a function $\textit{d(x,y)}$ that takes two points in the space as arguments and produces a real number that satisfies the following axioms:

1. $d(x,y) \ge 0$ (no negative distances)
2. $d(x,y) = 0$ if and only if $x = y$ (distances are positive, except for the distance from a point to itself)
3. $d(x,y) = d(y,x)$ (distance is symmetric)
4. $d(x,y) \le d(x,z) + d(z,y)$ (the triangle inequality)

The triangle inequality is the most complex condition. It says, intuitively, that to travel from x to y, we cannot obtain any benefit if we are forced to travel via some other point z. This axiom is what makes all distance measures behave as if distance describes the length of the shortest path from one point to another. 

<br />


## Euclidean Distance

<img src="../images/euclid_distance.png" alt="" width="300"/>

The most familiar distance measure is the one we normally think of as "distance". An $\textit{n-dimensional Euclidean space}$ is one where points are vectors of $\textit{n}$ real numbers. The conventional distance measure in this space, which we shall refer to as the $\textit{L}_{2}\textit{-norm}$, is defined:

<br />

$$
d([x_{1},x_{2},...,x_{n}], [y_{1},y_{2},...,y_{n}]) = \sqrt{\sum_{i=1}^{n} |x_{i} - y_{i}|^2}
\\
$$

<br />

That is, we square the distance in each dimension, sum the squares, and take the positive square root. There are other distance measures that have been used for Euclidean spaces. For any constant $\textit{r}$, we can define the $\textit{L}_{r}\textit{-norm}$ to be the distance measure $\textit{d}$ defined by:

<br />

$$
d([x_{1},x_{2},...,x_{n}], [y_{1},y_{2},...,y_{n}]) = (\sum_{i=1}^{n} |x_{i} - y_{i}|^r)^\frac{1}{r}
\\
$$

<br />

Another common distance measure is the $\textit{L}_{1}\textit{-norm}$, or $\textit{Manhattan distance}$. 

<br />

$$
d([x_{1},x_{2},...,x_{n}], [y_{1},y_{2},...,y_{n}]) = \sum_{i=1}^{n} |x_{i} - y_{i}|
\\
$$

<br />

In [12]:
import numpy as np

# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html
from sklearn.metrics import DistanceMetric

p1 = np.array([0., 0.])
p2 = np.array([1., 2.])

In [13]:
p1

array([0., 0.])

In [14]:
p2

array([1., 2.])

### Calculate L1 or "Manhattan" distance

In [15]:
np.sum(abs(p1 - p2))

3.0

In [16]:
dist = DistanceMetric.get_metric("manhattan")
dist.pairwise(np.vstack((p1, p2)))

array([[0., 3.],
       [3., 0.]])

### Calculate L2 or standard Euclidean distance

In [17]:
np.sqrt(np.sum(np.square(abs(p1 - p2))))

2.23606797749979

In [18]:
dist = DistanceMetric.get_metric("euclidean")
dist.pairwise(np.vstack((p1, p2)))

array([[0.        , 2.23606798],
       [2.23606798, 0.        ]])

## Non-Euclidean Space
There is an assumption being made when computing $\textit{L}_{r}\textit{-norm}$. Restated from above, 

> An $\textit{n-dimensional Euclidean space}$ is one where points are vectors of $\textit{n}$ real numbers. 

The assumption is that values between points exist and are real numbers. For many clustering and regression algorithms, average of points are needed, which is not possible on non-euclidean spaces. 


In [19]:
import random
import string

In [20]:
random_booleans = np.array([bool(random.getrandbits(1)) for _ in range(9)])
random_booleans.reshape(3,3)

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [21]:
random_ints = np.array([random.randint(0, 100) for _ in range(16)])
random_ints.reshape(4, 4)

array([[ 65,  95, 100,  24],
       [ 81,  16,  78,  75],
       [ 90,  80,  26,   1],
       [ 75,  44,  76,  99]])

In [22]:
random_letters = np.array([random.choice(string.ascii_letters) for _ in range(25)])
random_letters.reshape(5,5)

array([['W', 'y', 'B', 'K', 'X'],
       ['X', 'U', 'b', 'R', 'G'],
       ['z', 'T', 'R', 'C', 'm'],
       ['P', 'I', 'K', 'M', 'X'],
       ['d', 'n', 'p', 'L', 'Y']], dtype='<U1')

## Jaccard Distance
https://en.wikipedia.org/wiki/Jaccard_index

We define the $\textit{Jaccard distance}$ of sets as the inverse of $\textit{Jaccard similarity}$, or 1 minus the ratio of the sizes of the intersection and union of sets $\textit{A}$ and $\textit{B}$.

<br />
<br />
<div class="row" style="float: center; display: flex;">
    <img src="../images/union.png" alt="" width="300"/>
    <img src="../images/intersection.png" alt="" width="300"/>
</div>
<br />

In [23]:
set_a = np.array([bool(random.getrandbits(1)) for _ in range(9)])
set_b = np.array([bool(random.getrandbits(1)) for _ in range(9)])

In [24]:
set_a

array([ True, False,  True,  True, False, False,  True, False,  True])

In [25]:
set_b

array([ True, False,  True,  True,  True,  True, False,  True, False])

In [26]:
dist = DistanceMetric.get_metric("jaccard")
dist.pairwise(np.vstack((set_a, set_b)))

array([[0.   , 0.625],
       [0.625, 0.   ]])

## Edit Distance
https://en.wikipedia.org/wiki/Edit_distance

We define $\textit{Edit distance}$ as the distance between two strings ($x=x_1x_2...x_n$ and $y=y_1y_2...y_n$). There are many ways to measure "distance" here. One simple way is to measure the number of insertions and deletions needed to convert $x$ to $y$. 

In [32]:
# pip install fuzzywuzzy
from fuzzywuzzy import fuzz

In [33]:
word_1 = "bat"
word_2 = "cat"
word_3 = "dog"
word_4 = "map"

In [34]:
fuzz.ratio(word_1, word_2)

67

In [35]:
fuzz.ratio(word_1, word_3)

0

In [36]:
fuzz.ratio(word_1, word_4)

33